### ISSUE TITLE
error when exporting

### ISSUE THREAD

**Issue by davidvasandani** [vsco/jsonconsul#27]
Downloaded a release and tried to run `./jsonconsul export -json-values -prefix="helios"`

```
panic: interface conversion: interface is string, not map[string]interface {}

goroutine 1 [running]:
github.com/vsco/jsonconsul.consulToNestedMap(0x0, 0x0, 0xc20804a101, 0xc20803cae0, 0x0, 0x0)
    /Users/abhi/Dropbox/projects/gostuff/src/github.com/vsco/jsonconsul/consul.go:64 +0x747
github.com/vsco/jsonconsul.(*JsonExport).GenerateJson(0xc2080440f0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/abhi/Dropbox/projects/gostuff/src/github.com/vsco/jsonconsul/export.go:107 +0x8d
github.com/vsco/jsonconsul.(*JsonExport).Run(0xc2080440f0, 0x0, 0x0)
    /Users/abhi/Dropbox/projects/gostuff/src/github.com/vsco/jsonconsul/export.go:128 +0x4b
main.main()
    /Users/abhi/Dropbox/projects/gostuff/src/github.com/vsco/jsonconsul/cmd/main.go:42 +0x1b0

goroutine 7 [runnable]:
net/http.(*persistConn).readLoop(0xc20806e0b0)
    /Users/abhi/vsco/tools/vendor/go/1.4.2/src/net/http/transport.go:928 +0x9ce
created by net/http.(*Transport).dialConn
    /Users/abhi/vsco/tools/vendor/go/1.4.2/src/net/http/transport.go:660 +0xc9f

goroutine 8 [select]:
net/http.(*persistConn).writeLoop(0xc20806e0b0)
    /Users/abhi/vsco/tools/vendor/go/1.4.2/src/net/http/transport.go:945 +0x41d
created by net/http.(*Transport).dialConn
    /Users/abhi/vsco/tools/vendor/go/1.4.2/src/net/http/transport.go:661 +0xcbc
```

**Comment by rodaine** [comment]
Thanks for the report @davidneudorfer!

Working on a repro case. Could you supply us with a sample of your key names with the slashes? It looks like you may have a nested keyspace that may be causing the problem.
